spring:
  datasource:
#    url: jdbc:mysql://docker-mysql:3306/db_example
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
#    broker-url: tcp://activemq-test:61616
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

management:
  metrics.export.prometheus.enabled: true
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: '*'

#---
#spring:
#  profiles: container
#  datasource:
#    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}
